# -*- coding: utf-8 -*-
"""Divyajyothi_Car_Details_EDA_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ww7N09fpatZloiLTID1DUOZA8abJoWYQ

# Exploratory Data Analysis on a Cars Dataset

## Individual Project

**Student Name:** Divyajyothi

**Dataset:** Vehicle Dataset from CarDekho

**Dataset File:** Car_details_v3[1].csv

**Dataset Source:** Kaggle

**Tool Used:** Google Colab

## Objective

The objective of this project is to perform exploratory data analysis on a cars dataset. The analysis includes understanding the dataset, checking data quality, cleaning the data, calculating descriptive statistics, creating visualisations, identifying patterns and outliers, studying relationships between variables, and communicating meaningful findings.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

pd.set_option("display.max_columns", None)

print("Libraries imported successfully!")

file_path = "/content/Car_details_v3[1].csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

df.head()

"""## 1. Dataset Overview

The dataset contains information about used cars, including vehicle name, manufacturing year, selling price, kilometres driven, fuel type, seller type, transmission type, ownership category, mileage, engine capacity, maximum power, torque and number of seats.

The dataset is first examined for its structure, data types, missing values and duplicate records before performing exploratory analysis.

Find number of rows and columns
"""

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

"""Show column names"""

print("Column names:")

for column in df.columns:
    print(column)

"""Check data types"""

df.dtypes

df.info()

"""## 2. Data Quality Check — Missing Values

Missing values can affect statistical analysis and visualisations. Therefore, the dataset is checked for missing observations before the analysis.

"""

missing_values = df.isnull().sum()

missing_values

missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_table = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": missing_percentage.round(2)
})

missing_table

"""## 3. Duplicate Records

Duplicate records are checked because repeated rows can affect descriptive statistics and visual analysis.

"""

duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

"""## 4. Categorical Variable Analysis

The main categorical variables are fuel type, seller type, transmission type and ownership category. Their frequency distributions are examined to understand the composition of the dataset.

"""

categorical_columns = [
    "fuel",
    "seller_type",
    "transmission",
    "owner"
]

for column in categorical_columns:
    print("\n------------------------------")
    print(column)
    print("------------------------------")
    print(df[column].value_counts(dropna=False))

"""## 5. Data Cleaning

Some technical variables contain numerical values together with units or text. These variables are converted into numerical forms so that they can be used in statistical calculations and visualisations.

The original columns are retained, while separate cleaned numerical columns are created.

"""

df["mileage_num"] = pd.to_numeric(
    df["mileage"].astype(str).str.extract(
        r"([0-9]+(?:\.[0-9]+)?)"
    )[0],
    errors="coerce"
)

df["engine_num"] = pd.to_numeric(
    df["engine"].astype(str).str.extract(
        r"([0-9]+(?:\.[0-9]+)?)"
    )[0],
    errors="coerce"
)

df["max_power_num"] = pd.to_numeric(
    df["max_power"].astype(str).str.extract(
        r"([0-9]+(?:\.[0-9]+)?)"
    )[0],
    errors="coerce"
)

df["torque_num"] = pd.to_numeric(
    df["torque"].astype(str).str.extract(
        r"([0-9]+(?:\.[0-9]+)?)"
    )[0],
    errors="coerce"
)

print("Technical columns converted successfully.")

"""Check the cleaned data"""

df[
    [
        "mileage",
        "mileage_num",
        "engine",
        "engine_num",
        "max_power",
        "max_power_num",
        "torque",
        "torque_num"
    ]
].head(10)

"""## 6. Descriptive Statistics

Descriptive statistics are calculated for the main numerical variables to understand their central tendency, variation and range.

"""

df[
    [
        "year",
        "selling_price",
        "km_driven",
        "mileage_num",
        "engine_num",
        "max_power_num",
        "seats"
    ]
].describe()

"""## 7. Univariate Analysis — Selling Price

The distribution of selling prices is examined using a histogram to understand the range and shape of vehicle prices.

"""

plt.figure(figsize=(10, 5))

sns.histplot(
    df["selling_price"],
    bins=40,
    kde=True
)

plt.title("Distribution of Selling Price")
plt.xlabel("Selling Price")
plt.ylabel("Number of Cars")

plt.show()

"""### Observation

The selling price distribution shows substantial variation among the cars. The distribution is right-skewed, with a relatively small number of vehicles having very high selling prices.

## 8. Fuel Type Analysis

A count plot is used to examine the distribution of vehicles across different fuel types.
"""

plt.figure(figsize=(8, 5))

sns.countplot(data=df, x="fuel")

plt.title("Distribution of Cars by Fuel Type")
plt.xlabel("Fuel Type")
plt.ylabel("Number of Cars")

plt.show()

"""### Observation

The chart shows the relative frequency of each fuel category. Diesel and petrol account for the majority of the observations, while the other fuel categories occur less frequently.

## 9. Transmission Analysis

The transmission variable is analysed to compare the number of manual and automatic vehicles in the dataset.
"""

plt.figure(figsize=(8, 5))

sns.countplot(data=df, x="transmission")

plt.title("Distribution of Cars by Transmission")
plt.xlabel("Transmission")
plt.ylabel("Number of Cars")

plt.show()

"""### Observation

Manual transmission vehicles form the larger share of the dataset, while automatic vehicles represent a smaller proportion.

## 10. Seller Type Analysis

The seller type distribution is examined to understand whether the cars are mainly listed by individuals or dealers.
"""

plt.figure(figsize=(8, 5))

sns.countplot(data=df, x="seller_type")

plt.title("Distribution of Cars by Seller Type")
plt.xlabel("Seller Type")
plt.ylabel("Number of Cars")

plt.xticks(rotation=15)

plt.show()

"""### Observation

Individual sellers represent the largest seller category in the dataset, followed by dealers and trustmark dealers.

## 11. Bivariate Analysis — Year vs Selling Price

The relationship between vehicle manufacturing year and selling price is examined using a scatter plot.
"""

plt.figure(figsize=(10, 6))

sns.scatterplot(
    data=df,
    x="year",
    y="selling_price",
    alpha=0.5
)

plt.title("Year vs Selling Price")
plt.xlabel("Year")
plt.ylabel("Selling Price")

plt.show()

"""### Observation

The scatter plot allows the relationship between vehicle age and selling price to be examined. Newer vehicles generally appear across higher price ranges, although there is considerable variation.

## 12. Bivariate Analysis — Kilometres Driven vs Selling Price

The relationship between kilometres driven and selling price is examined to understand whether vehicle usage is associated with price differences.
"""

plt.figure(figsize=(10, 6))

sns.scatterplot(
    data=df,
    x="km_driven",
    y="selling_price",
    alpha=0.5
)

plt.title("Kilometres Driven vs Selling Price")
plt.xlabel("Kilometres Driven")
plt.ylabel("Selling Price")

plt.show()

"""### Observation

The plot shows considerable variation in selling price across kilometres driven. In general, vehicles with higher kilometres driven tend to appear at lower selling-price levels, although the relationship is not perfectly linear.

## 13. Outlier Analysis

Box plots are used to identify unusually high or low observations in important numerical variables.
"""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.boxplot(
    x=df["selling_price"],
    ax=axes[0]
)

axes[0].set_title("Selling Price Outliers")
axes[0].set_xlabel("Selling Price")

sns.boxplot(
    x=df["km_driven"],
    ax=axes[1]
)

axes[1].set_title("Kilometres Driven Outliers")
axes[1].set_xlabel("Kilometres Driven")

plt.tight_layout()
plt.show()

"""### Observation

The box plots show extreme observations in both selling price and kilometres driven. These observations should be recognised during interpretation because extreme values can influence summary statistics.

## 14. Multivariate Analysis — Correlation

A correlation matrix is used to examine relationships between the main numerical variables.
"""

correlation_columns = [
    "year",
    "selling_price",
    "km_driven",
    "mileage_num",
    "engine_num",
    "max_power_num",
    "torque_num",
    "seats"
]

correlation_matrix = df[correlation_columns].corr()

plt.figure(figsize=(10, 7))

sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Heatmap")

plt.show()

print("Correlation with selling price:")

correlation_matrix["selling_price"].sort_values(
    ascending=False
)

"""## 15. Key Findings

Based on the descriptive statistics and visualisations, the following findings were identified:

1. Diesel and petrol vehicles represent the majority of observations in the dataset.

2. Manual transmission vehicles are considerably more common than automatic vehicles.

3. Individual sellers form the largest seller category.

4. Selling prices show substantial variation and a right-skewed distribution.

5. Newer vehicles generally appear in higher selling-price ranges.

6. Kilometres driven shows a generally negative relationship with selling price.

7. The correlation analysis shows meaningful relationships between selling price and several vehicle characteristics.

8. The box plots indicate the presence of extreme observations in variables such as selling price and kilometres driven.

## 16. Limitations

The dataset represents used-car listings and therefore may not represent the complete used-car market.

Some variables contain missing observations or require cleaning before numerical analysis.

The dataset contains extreme values that may influence descriptive statistics.

Important factors such as exact vehicle condition, accident history, service history and negotiation outcomes are not available in the dataset.

Correlation indicates association between variables and does not establish causation.

## 17. Conclusion

The exploratory data analysis provided an overview of the structure, quality and characteristics of the used-car dataset. Data-quality checks identified missing values and duplicate records, while cleaning converted important technical variables into usable numerical forms.

Descriptive statistics and visualisations revealed substantial variation in selling prices, vehicle usage, fuel types, transmission types and ownership categories. The bivariate and correlation analyses also showed relationships between vehicle characteristics and selling price.

Overall, the EDA demonstrates how systematic data cleaning, statistical summaries and visualisation can be used to identify meaningful patterns and communicate insights from a real-world automobile dataset.
"""